sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"

matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8-dev
    env: TOXENV=py38
  - python: pypy3
    env: TOXENV=pypy

install:
    - pip install -U pip
    - pip install tox codecov

script:
    - tox -e $TOXENV

after_success:
    - codecov
